version: 0.0
os: linux
files:
  - source: /app.py
    destination: /home/ec2-user/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user