version: 0.0
os: linux
files:
  - source: /app.py
    destination: /home/ec2-user/
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
permissions:
  - object: /home/ec2-user
    pattern: "app.py"
    owner: ec2-user
    group: ec2-user
    mode: 775
    type:
      - file